# Generated by Django 5.2.6 on 2025-11-06 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0001_initial'),
        ('pacientes', '0003_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='odontologos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora'],
                'unique_together': {('fecha', 'hora', 'odontologo')},
            },
        ),
    ]
