# Generated by Django 5.2.6 on 2025-11-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0001_initial'),
        ('pacientes', '0004_turno'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Estado de Tratamiento',
                'verbose_name_plural': 'Estados de Tratamiento',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('duracion_estimada', models.PositiveIntegerField(help_text='Duración estimada en meses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pacientes.estadotratamiento')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='odontologos.odontologo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
                'ordering': ['-created_at'],
            },
        ),
    ]
