# Generated by Django 5.2.6 on 2025-11-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_estadotratamiento_tratamiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odontograma', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
            },
        ),
        migrations.CreateModel(
            name='OdontogramaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fdi', models.IntegerField()),
                ('superficie', models.IntegerField(choices=[(1, 'Oclusal/Incisal'), (2, 'Mesial'), (3, 'Distal'), (4, 'Vestibular'), (5, 'Lingual/Palatina')])),
                ('color_codigo', models.CharField(choices=[('blanco', 'Sano'), ('rojo', 'Caries'), ('verde', 'Sellante'), ('gris', 'Amalgama'), ('azul', 'Composite'), ('negro', 'Extracción Indicada')], default='blanco', max_length=10)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='pacientes.odontograma')),
            ],
            options={
                'verbose_name': 'Datos del Odontograma',
                'verbose_name_plural': 'Datos de Odontogramas',
                'ordering': ['fdi', 'superficie'],
                'unique_together': {('odontograma', 'fdi', 'superficie')},
            },
        ),
    ]
