# Generated by Django 5.2.8 on 2025-11-09 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_odontograma_odontogramadatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='evoluciones/%Y/%m/')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='pacientes.tratamiento')),
            ],
            options={
                'verbose_name': 'Evolución',
                'verbose_name_plural': 'Evoluciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
