# Generated by Django 5.2 on 2025-11-10 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_odontograma_odontogramadatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='recordatorio_programado',
            field=models.BooleanField(default=False),
        ),
    ]
