# Generated by Django 5.2 on 2025-11-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_evolucion'),
        ('pacientes', '0007_turno_recordatorio_programado'),
    ]

    operations = [
    ]
